logging:
  level:
    root: info
server:
  port: 88
spring:
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      port: 6379
      database: 0
      host: touched-yak-39531.upstash.io
      password: AZprAAIjcDE1N2VhNmU1OGMyYzA0ZmQzODcwYmM0YzQ0MWI4NzQ0MXAxMA
      username: default
      ssl:
        enabled: true
  config:
    import: nacos:secretblog_gateway_application.yml
  application:
    name: secret-gateway
  cloud:
    nacos:
      server-addr: 35.209.184.74:8848
      password: nacos
      username: nacos
      discovery:
        server-addr: 35.209.184.74:8848
      config:
        server-addr: 35.209.184.74:8848
        timeout: 300000
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: article_route
          uri: lb://secret-article
          predicates:
            - Path=/api/article/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}
        - id: user_route
          uri: lb://secret-user
          predicates:
            - Path=/api/ums/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}
        - id: storage_route
          uri: lb://secret-storage
          predicates:
            - Path=/api/sms/**
          filters:
            - RewritePath=/api/?(?<segment>.*), /$\{segment}