spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.91.133:3306/secretblog_ams?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
  application:
    name: secret-article
  cloud:
    nacos:
      server-addr: 192.168.91.133:8848
      discovery:
        server-addr: 192.168.91.133:8848
  config:
    import: nacos:application.yml
logging:
  level:
    root: info
server:
  port: 21000
mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.shijiawei.secretblog.article.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn